export const mock_list = [
  {
    title: '',
    description: '',
    buttonText: 'DEVILS CLUB DRY SUIT',
    img: './assets/devilsclub.webp',
    imgDescription: ' ',
    price: '$1399.00',
  },
  {
    title: '',
    description: '',
    buttonText: "WOMEN'S SAHALIE DRY SUIT",
    img: './assets/sahalie.webp',
    imgDescription: 'not found',
    price: '$1359.00',
  },
  {
    title: '',
    description: '',
    buttonText: '7FIGURE DRY SUIT',
    img: './assets/drysuit7figurered.jpg',
    imgDescription: 'not found',
    price: '$1399.00',
  },

  {
    title: '',
    description: '',
    buttonText: "WOMEN'S APHRODITE DRY SUIT",
    img: './assets/aphrodite.webp',
    imgDescription: 'not found',
    price: '$1359.00',
  },
  {
    title: '',
    description: '',
    buttonText: "WOMEN'S APHRODITE DRY SUIT 2022",
    img: './assets/aphrodite22.webp',
    imgDescription: 'not found',
    price: '$999.00',
  },
  {
    title: '',
    description: '',
    buttonText: "DEVIL'S CLUB DRY SUIT 2022",
    img: './assets/22devil.webp',
    imgDescription: 'not found',
    price: '$999.00',
  },
  {
    title: '',
    description: '',
    buttonText: '7FIGURE DRY SUIT 2022',
    img: './assets/drysuit7figureblue.jpg',
    imgDescription: 'not found',
    price: '$999.00',
  },
];
