export const mock_list = [
  {
    title: '',
    description: '',
    buttonText: 'DEVILS CLUB DRY TOP',
    img: './assets/deviltop.webp',
    imgDescription: ' ',
    price: '$489.00',
  },
  {
    title: '',
    description: '',
    buttonText: '7FIGURE DRY TOP',
    img: './assets/7figuretop.webp',
    imgDescription: 'not found',
    price: '$489.00',
  },
  {
    title: '',
    description: '',
    buttonText: '7FIGURE DRY TOP 2022',
    img: './assets/7figuretop22.webp',
    imgDescription: 'not found',
    price: '$449.00',
  },
  {
    title: '',
    description: '',
    buttonText: "DEVIL'S CLUB DRY TOP 2022",
    img: './assets/devildry.webp',
    imgDescription: 'not found',
    price: '$329.00',
  },
  {
    title: '',
    description: '',
    buttonText: "WOMEN'S APHRODITE DRY TOP",
    img: './assets/girltop.webp',
    imgDescription: 'not found',
    price: '$329.00',
  },
  {
    title: '',
    description: '',
    buttonText: "WOMEN'S APHRODITE DRY TOP 2022",
    img: './assets/girltop22.webp',
    imgDescription: 'not found',
    price: '$289.00',
  },
];
